-- Mangos or Trinitycore 数据库中文支持
-- version 1.0
-- https://git.oschina.net/686500/Wow-ChineseDB

UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='影牙城堡的(入口)' WHERE (`mapId`='33') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='暴风城监狱(入口)' WHERE (`mapId`='34') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='迪蒙特荒野 - 死亡矿井(入口)' WHERE (`mapId`='36') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='贫瘠之地——哀嚎洞穴' WHERE (`mapId`='43') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='贫瘠之地 - 剃刀沼泽(入口)' WHERE (`mapId`='47') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='黑暗深渊(入口)' WHERE (`mapId`='48') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥达曼 - 守护者大厅(入口)' WHERE (`mapId`='70') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='丹莫罗 - 诺莫瑞根(入口)' WHERE (`mapId`='90') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='悲伤沼泽 - 阿塔哈卡神庙(入口)' WHERE (`mapId`='109') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='贫瘠之地 - 剃刀高地(入口)' WHERE (`mapId`='129') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='血色修道院-墓地(入口)' WHERE (`mapId`='189') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='塔纳利斯 - 祖尔法拉克(入口)' WHERE (`mapId`='209') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='黑石山 - 黑石塔' WHERE (`mapId`='229') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='灼热峡谷 - 黑石山' WHERE (`mapId`='230') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥妮克希亚的巢穴(入口)' WHERE (`mapId`='249') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥妮克希亚的巢穴(入口)' WHERE (`mapId`='249') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`='你必须完成任务“返回安多尔姆身边”才能进入。', `comment`='时光之穴:黑暗之门(入口)' WHERE (`mapId`='269') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`='你必须完成任务“返回安多尔姆身边”才能进入。', `comment`='时光之穴:黑暗之门(入口)' WHERE (`mapId`='269') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='西瘟疫之地 - 凯尔达隆 - 通灵学院(入口)' WHERE (`mapId`='289') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='祖尔格拉布(入口)' WHERE (`mapId`='309') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='东瘟疫之地 - 斯坦索姆' WHERE (`mapId`='329') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='玛拉顿' WHERE (`mapId`='349') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥格瑞玛 - 怒焰裂谷' WHERE (`mapId`='389') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='黑石深渊 - 熔火之桥' WHERE (`mapId`='409') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='厄运之槌西部(亡灵区)' WHERE (`mapId`='429') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='黑翼之巢-黑石山-东部王国' WHERE (`mapId`='469') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='安其拉废墟(外面)' WHERE (`mapId`='509') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='安其拉神庙(外面)' WHERE (`mapId`='531') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='卡拉赞，主要(入口)' WHERE (`mapId`='532') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='纳克萨玛斯' WHERE (`mapId`='533') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='纳克萨玛斯' WHERE (`mapId`='533') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='海加尔山战役，联盟基地(入口)' WHERE (`mapId`='534') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='破碎大厅(入口)' WHERE (`mapId`='540') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='破碎大厅(入口)' WHERE (`mapId`='540') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='鲜血熔炉 (入口)' WHERE (`mapId`='542') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='鲜血熔炉 (入口)' WHERE (`mapId`='542') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='地狱火堡垒  (入口)' WHERE (`mapId`='543') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='地狱火堡垒  (入口)' WHERE (`mapId`='543') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='玛瑟里顿的巢穴 (入口)' WHERE (`mapId`='544') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='蒸汽洞窟  (入口)' WHERE (`mapId`='545') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='蒸汽洞窟  (入口)' WHERE (`mapId`='545') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='幽暗沼泽 (入口)' WHERE (`mapId`='546') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='幽暗沼泽 (入口)' WHERE (`mapId`='546') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奴隶围栏 (入口)' WHERE (`mapId`='547') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奴隶围栏 (入口)' WHERE (`mapId`='547') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='毒蛇神殿 (入口)' WHERE (`mapId`='548') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='风暴之眼(入口)' WHERE (`mapId`='550') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='风暴要塞:拱廊区(入口)' WHERE (`mapId`='552') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='风暴要塞:拱廊区(入口)' WHERE (`mapId`='552') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='生态船 (入口)' WHERE (`mapId`='553') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='生态船 (入口)' WHERE (`mapId`='553') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='能源舰  (入口)' WHERE (`mapId`='554') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='能源舰  (入口)' WHERE (`mapId`='554') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='暗影迷宫  (入口)' WHERE (`mapId`='555') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='暗影迷宫  (入口)' WHERE (`mapId`='555') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='塞司克大厅  (入口)' WHERE (`mapId`='556') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='塞司克大厅  (入口)' WHERE (`mapId`='556') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='法力陵墓  (入口)' WHERE (`mapId`='557') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='法力陵墓  (入口)' WHERE (`mapId`='557') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥金顿大厅  (入口)' WHERE (`mapId`='558') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥金顿大厅  (入口)' WHERE (`mapId`='558') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='时光之穴，旧希尔斯布莱德丘陵  (入口)' WHERE (`mapId`='560') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='时光之穴，旧希尔斯布莱德丘陵  (入口)' WHERE (`mapId`='560') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='黑暗神庙  (入口)' WHERE (`mapId`='564') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='格鲁尔的巢穴  (入口)' WHERE (`mapId`='565') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='祖阿曼  (入口)' WHERE (`mapId`='568') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='乌特加德城堡  (入口)' WHERE (`mapId`='574') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='乌特加德城堡  (入口)' WHERE (`mapId`='574') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='乌特加德之巅  (入口)' WHERE (`mapId`='575') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='乌特加德之巅  (入口)' WHERE (`mapId`='575') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥核之心  (入口)' WHERE (`mapId`='576') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥核之心  (入口)' WHERE (`mapId`='576') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥核之眼  (入口)' WHERE (`mapId`='578') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥核之眼  (入口)' WHERE (`mapId`='578') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='太阳井高地  (入口)' WHERE (`mapId`='580') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`='你必须完成任务“大难不死”才能进入。', `comment`='魔导师平台  (入口)' WHERE (`mapId`='585') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`='你必须完成任务“大难不死”才能进入。', `comment`='魔导师平台  (入口)' WHERE (`mapId`='585') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='时光之穴：净化斯坦索姆  (入口)' WHERE (`mapId`='595') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='时光之穴：净化斯坦索姆  (入口)' WHERE (`mapId`='595') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥达尔:石头大厅  (入口)' WHERE (`mapId`='599') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥达尔:石头大厅  (入口)' WHERE (`mapId`='599') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='达克萨隆要塞  (入口)' WHERE (`mapId`='600') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='达克萨隆要塞  (入口)' WHERE (`mapId`='600') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='艾兹卓-尼鲁布  (入口)' WHERE (`mapId`='601') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='艾兹卓-尼鲁布  (入口)' WHERE (`mapId`='601') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥达尔:光明大厅  (入口)' WHERE (`mapId`='602') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥达尔:光明大厅  (入口)' WHERE (`mapId`='602') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥杜尔 Raid  (入口)' WHERE (`mapId`='603') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='奥杜尔 Raid  (入口)' WHERE (`mapId`='603') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='古达克 (北入口)' WHERE (`mapId`='604') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='古达克 (北入口)' WHERE (`mapId`='604') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='紫罗兰监狱  (入口)' WHERE (`mapId`='608') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='紫罗兰监狱  (入口)' WHERE (`mapId`='608') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='黑色大厅,黑曜石圣殿  (入口)' WHERE (`mapId`='615') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='黑色大厅,黑曜石圣殿  (入口)' WHERE (`mapId`='615') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='永恒之眼  (入口)' WHERE (`mapId`='616') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='永恒之眼  (入口)' WHERE (`mapId`='616') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='安卡赫特古代王国  (入口)' WHERE (`mapId`='619') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='安卡赫特古代王国  (入口)' WHERE (`mapId`='619') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='阿尔卡冯的宝库  (入口)' WHERE (`mapId`='624') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='阿尔卡冯的宝库  (入口)' WHERE (`mapId`='624') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`='你必须拥有成就“冰封王座（25人）”才能进入。', `comment`='冰冠城塞  (入口)' WHERE (`mapId`='631') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`='你必须拥有成就“冰封王座（25人）”才能进入。', `comment`='冰冠城塞  (入口)' WHERE (`mapId`='631') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`='你必须拥有成就“冰封王座（25人）”才能进入。', `comment`='冰冠城塞  (入口)' WHERE (`mapId`='631') AND (`difficulty`='2');
UPDATE `access_requirement` SET `quest_failed_text`='你必须拥有成就“冰封王座（25人）”才能进入。', `comment`='冰冠城塞  (入口)' WHERE (`mapId`='631') AND (`difficulty`='3');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='灵魂熔炉  (入口)' WHERE (`mapId`='632') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='灵魂熔炉  (入口)' WHERE (`mapId`='632') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='十字军的试炼' WHERE (`mapId`='649') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='十字军的试炼' WHERE (`mapId`='649') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='十字军的试炼' WHERE (`mapId`='649') AND (`difficulty`='2');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='十字军的试炼' WHERE (`mapId`='649') AND (`difficulty`='3');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='十字军的试炼' WHERE (`mapId`='650') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='十字军的试炼' WHERE (`mapId`='650') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`='你必须完成任务“痛苦灵魂的回声”才能进入。', `comment`='萨伦之渊  (入口)' WHERE (`mapId`='658') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`='你必须完成任务“痛苦灵魂的回声”才能进入。', `comment`='萨伦之渊  (入口)' WHERE (`mapId`='658') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`='你必须完成任务“深渊的裁决”才能进入。', `comment`='倒影大厅  (入口)' WHERE (`mapId`='668') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`='你必须完成任务“深渊的裁决”才能进入。', `comment`='倒影大厅  (入口)' WHERE (`mapId`='668') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='晶红圣所  (入口)' WHERE (`mapId`='724') AND (`difficulty`='0');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='晶红圣所  (入口)' WHERE (`mapId`='724') AND (`difficulty`='1');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='晶红圣所  (入口)' WHERE (`mapId`='724') AND (`difficulty`='2');
UPDATE `access_requirement` SET `quest_failed_text`=NULL, `comment`='晶红圣所  (入口)' WHERE (`mapId`='724') AND (`difficulty`='3');