-- Mangos or Trinitycore 数据库中文支持
-- version 1.0
-- https://git.oschina.net/686500/Wow-ChineseDB

UPDATE `areatrigger_tavern` SET `name`='西部荒野 - 哨兵岭旅店' WHERE (`id`='71');
UPDATE `areatrigger_tavern` SET `name`='艾尔文森林 - 闪金镇 - 狮王之傲旅店' WHERE (`id`='562');
UPDATE `areatrigger_tavern` SET `name`='赤脊山 - 湖畔旅店' WHERE (`id`='682');
UPDATE `areatrigger_tavern` SET `name`='暮色森林 - 夜色 - 血色旅店' WHERE (`id`='707');
UPDATE `areatrigger_tavern` SET `name`='希尔斯布莱德丘陵 - 南海镇的旅店' WHERE (`id`='708');
UPDATE `areatrigger_tavern` SET `name`='尘泥沼泽 - 塞拉摩岛' WHERE (`id`='709');
UPDATE `areatrigger_tavern` SET `name`='丹莫罗 - 卡拉诺斯 - 雷酒厂' WHERE (`id`='710');
UPDATE `areatrigger_tavern` SET `name`='洛克莫丹 - 在塞尔萨玛 - 烈酒旅店' WHERE (`id`='712');
UPDATE `areatrigger_tavern` SET `name`='湿地 - 米奈希尔港 - 深水酒馆' WHERE (`id`='713');
UPDATE `areatrigger_tavern` SET `name`='泰达希尔 - 多兰纳尔' WHERE (`id`='715');
UPDATE `areatrigger_tavern` SET `name`='黑海岸 - 奥伯丁' WHERE (`id`='716');
UPDATE `areatrigger_tavern` SET `name`='梣谷 - 阿斯特兰纳' WHERE (`id`='717');
UPDATE `areatrigger_tavern` SET `name`='提里斯法林地 - 布瑞尔 - 恐惧之末旅店' WHERE (`id`='719');
UPDATE `areatrigger_tavern` SET `name`='银松森林' WHERE (`id`='720');
UPDATE `areatrigger_tavern` SET `name`='希尔斯布莱德丘陵' WHERE (`id`='721');
UPDATE `areatrigger_tavern` SET `name`='莫高雷' WHERE (`id`='722');
UPDATE `areatrigger_tavern` SET `name`='贫瘠之地' WHERE (`id`='742');
UPDATE `areatrigger_tavern` SET `name`='贫瘠之地' WHERE (`id`='743');
UPDATE `areatrigger_tavern` SET `name`='杜洛塔' WHERE (`id`='843');
UPDATE `areatrigger_tavern` SET `name`='悲伤沼泽' WHERE (`id`='844');
UPDATE `areatrigger_tavern` SET `name`='荆棘谷' WHERE (`id`='862');
UPDATE `areatrigger_tavern` SET `name`='贫瘠之地' WHERE (`id`='982');
UPDATE `areatrigger_tavern` SET `name`='血谜岛 - 血色守望旅店' WHERE (`id`='4241');
UPDATE `areatrigger_tavern` SET `name`='石爪山脉' WHERE (`id`='1022');
UPDATE `areatrigger_tavern` SET `name`='塔纳利斯' WHERE (`id`='1023');
UPDATE `areatrigger_tavern` SET `name`='菲拉斯' WHERE (`id`='1024');
UPDATE `areatrigger_tavern` SET `name`='菲拉斯' WHERE (`id`='1025');
UPDATE `areatrigger_tavern` SET `name`='废地' WHERE (`id`='1606');
UPDATE `areatrigger_tavern` SET `name`='阿拉希高地' WHERE (`id`='1646');
UPDATE `areatrigger_tavern` SET `name`='凄凉之地' WHERE (`id`='2266');
UPDATE `areatrigger_tavern` SET `name`='凄凉之地' WHERE (`id`='2267');
UPDATE `areatrigger_tavern` SET `name`='千针石林' WHERE (`id`='2286');
UPDATE `areatrigger_tavern` SET `name`='冬泉谷' WHERE (`id`='2287');
UPDATE `areatrigger_tavern` SET `name`='梣谷' WHERE (`id`='2610');
UPDATE `areatrigger_tavern` SET `name`='暴风城休息站' WHERE (`id`='2786');
UPDATE `areatrigger_tavern` SET `name`='安宁旅店' WHERE (`id`='4108');
UPDATE `areatrigger_tavern` SET `name`='碧蓝岗哨旅店' WHERE (`id`='4240');
UPDATE `areatrigger_tavern` SET `name`='萨尔玛旅店' WHERE (`id`='4336');
UPDATE `areatrigger_tavern` SET `name`='荣耀堡旅店' WHERE (`id`='4337');
UPDATE `areatrigger_tavern` SET `name`='萨布拉金旅店' WHERE (`id`='4373');
UPDATE `areatrigger_tavern` SET `name`='如卡拉达尔快捷酒店' WHERE (`id`='4375');
UPDATE `areatrigger_tavern` SET `name`='泰拉旅店' WHERE (`id`='4376');
UPDATE `areatrigger_tavern` SET `name`='艾兰理堡垒旅店' WHERE (`id`='4377');
UPDATE `areatrigger_tavern` SET `name`='塞纳里奥避难所' WHERE (`id`='4382');
UPDATE `areatrigger_tavern` SET `name`='猎鹰之翼广场旅店' WHERE (`id`='4486');
UPDATE `areatrigger_tavern` SET `name`='影月村旅店' WHERE (`id`='4526');
UPDATE `areatrigger_tavern` SET `name`='蛮锤要塞旅店' WHERE (`id`='4528');
UPDATE `areatrigger_tavern` SET `name`='摩克纳萨尔村旅店' WHERE (`id`='4595');
UPDATE `areatrigger_tavern` SET `name`='星光圣所旅店' WHERE (`id`='4607');
UPDATE `areatrigger_tavern` SET `name`='泰伦多尔旅店' WHERE (`id`='4374');
UPDATE `areatrigger_tavern` SET `name`='奥雷伯尔港旅店' WHERE (`id`='4383');
UPDATE `areatrigger_tavern` SET `name`='特尔哈曼神庙旅店' WHERE (`id`='4381');
UPDATE `areatrigger_tavern` SET `name`='希尔瓦纳旅店' WHERE (`id`='4499');
UPDATE `areatrigger_tavern` SET `name`='托斯利基地旅店' WHERE (`id`='4558');
UPDATE `areatrigger_tavern` SET `name`='雷霆王村旅店' WHERE (`id`='4494');
UPDATE `areatrigger_tavern` SET `name`='永恒树林旅店' WHERE (`id`='4640');
UPDATE `areatrigger_tavern` SET `name`='52区旅店' WHERE (`id`='4521');
UPDATE `areatrigger_tavern` SET `name`='风暴之尖旅店' WHERE (`id`='4555');
UPDATE `areatrigger_tavern` SET `name`='萨塔祭坛' WHERE (`id`='4577');
UPDATE `areatrigger_tavern` SET `name`='斯坦恩布莱德' WHERE (`id`='178');
UPDATE `areatrigger_tavern` SET `name`='蛮锤城堡' WHERE (`id`='1042');
UPDATE `areatrigger_tavern` SET `name`='恶齿村' WHERE (`id`='3690');
UPDATE `areatrigger_tavern` SET `name`='格罗姆高营地' WHERE (`id`='3886');
UPDATE `areatrigger_tavern` SET `name`='圣光之愿礼拜堂' WHERE (`id`='4058');
UPDATE `areatrigger_tavern` SET `name`='塞纳里奥城堡' WHERE (`id`='3985');
UPDATE `areatrigger_tavern` SET `name`='石爪峰' WHERE (`id`='4090');
UPDATE `areatrigger_tavern` SET `name`='幽暗城' WHERE (`id`='3547');
UPDATE `areatrigger_tavern` SET `name`='铁炉堡大门' WHERE (`id`='4769');
UPDATE `areatrigger_tavern` SET `name`='泥链营地旅店' WHERE (`id`='4714');
UPDATE `areatrigger_tavern` SET `name`='蕨墙村旅店' WHERE (`id`='4775');
UPDATE `areatrigger_tavern` SET `name`='奎尔丹纳斯岛，日境港酒店' WHERE (`id`='4847');
UPDATE `areatrigger_tavern` SET `name`='骁勇要塞旅店' WHERE (`id`='4961');
UPDATE `areatrigger_tavern` SET `name`='嘶轴简易机场旅店' WHERE (`id`='4867');
UPDATE `areatrigger_tavern` SET `name`='昂纽沛旅店' WHERE (`id`='4977');
UPDATE `areatrigger_tavern` SET `name`='坦卡雷村旅店' WHERE (`id`='4868');
UPDATE `areatrigger_tavern` SET `name`='战歌堡' WHERE (`id`='4910');
UPDATE `areatrigger_tavern` SET `name`='博格洛克前哨旅店' WHERE (`id`='4861');
UPDATE `areatrigger_tavern` SET `name`='冬蹄营地旅店' WHERE (`id`='4755');
UPDATE `areatrigger_tavern` SET `name`='威德瓦堡垒旅店' WHERE (`id`='4756');
UPDATE `areatrigger_tavern` SET `name`='阿格玛之锤' WHERE (`id`='5045');
UPDATE `areatrigger_tavern` SET `name`='繁星之眠' WHERE (`id`='4964');
UPDATE `areatrigger_tavern` SET `name`='琥珀松小屋旅店' WHERE (`id`='4965');
UPDATE `areatrigger_tavern` SET `name`='西荒兵团驻营' WHERE (`id`='4966');
UPDATE `areatrigger_tavern` SET `name`='欧尼克瓦营地' WHERE (`id`='4967');
UPDATE `areatrigger_tavern` SET `name`='征服堡' WHERE (`id`='4970');
UPDATE `areatrigger_tavern` SET `name`='默亚基港' WHERE (`id`='4975');
UPDATE `areatrigger_tavern` SET `name`='卡玛廓' WHERE (`id`='4976');
UPDATE `areatrigger_tavern` SET `name`='毒怨之地' WHERE (`id`='4979');
UPDATE `areatrigger_tavern` SET `name`='温特加德要塞' WHERE (`id`='4993');
UPDATE `areatrigger_tavern` SET `name`='矛生驻营' WHERE (`id`='5030');
UPDATE `areatrigger_tavern` SET `name`='银白看台' WHERE (`id`='5062');
UPDATE `areatrigger_tavern` SET `name`='辛讬加' WHERE (`id`='5164');
UPDATE `areatrigger_tavern` SET `name`='霜堡' WHERE (`id`='5182');
UPDATE `areatrigger_tavern` SET `name`='K3' WHERE (`id`='5183');
UPDATE `areatrigger_tavern` SET `name`='布伦希尔达村' WHERE (`id`='5200');
UPDATE `areatrigger_tavern` SET `name`='石崖避难所' WHERE (`id`='5204');
UPDATE `areatrigger_tavern` SET `name`='奈辛瓦里营地' WHERE (`id`='5217');
UPDATE `areatrigger_tavern` SET `name`='银白先锋' WHERE (`id`='5227');
UPDATE `areatrigger_tavern` SET `name`='坦卡罗营地' WHERE (`id`='5323');
UPDATE `areatrigger_tavern` SET `name`='卡萨斯平台' WHERE (`id`='5327');
UPDATE `areatrigger_tavern` SET `name`='镇西旅店' WHERE (`id`='4753');
UPDATE `areatrigger_tavern` SET `name`='晴风村旅店' WHERE (`id`='4265');
UPDATE `areatrigger_tavern` SET `name`='奈辛瓦里远征队营地' WHERE (`id`='98');
UPDATE `areatrigger_tavern` SET `name`='安宁地旅店（上层）' WHERE (`id`='4109');
UPDATE `areatrigger_tavern` SET `name`='塞纳里奥难民 - 外旅店' WHERE (`id`='4300');
UPDATE `areatrigger_tavern` SET `name`='石堡旅店' WHERE (`id`='4378');
UPDATE `areatrigger_tavern` SET `name`='猎鹰岗哨旅店' WHERE (`id`='4380');
UPDATE `areatrigger_tavern` SET `name`='旧希尔斯布莱德丘陵旅店' WHERE (`id`='4498');
UPDATE `areatrigger_tavern` SET `name`='圣殿的星星旅店（上层）' WHERE (`id`='4608');
UPDATE `areatrigger_tavern` SET `name`='龙眠神殿' WHERE (`id`='5314');
UPDATE `areatrigger_tavern` SET `name`='龙眠神殿' WHERE (`id`='5315');
UPDATE `areatrigger_tavern` SET `name`='龙眠神殿' WHERE (`id`='5316');
UPDATE `areatrigger_tavern` SET `name`='龙眠神殿...' WHERE (`id`='5317');
UPDATE `areatrigger_tavern` SET `name`='格罗玛什坠毁点' WHERE (`id`='5360');