-- Mangos or Trinitycore 数据库中文支持
-- version 1.0
-- https://git.oschina.net/686500/Wow-ChineseDB

UPDATE `areatrigger_teleport` SET `Name`='血色修道院西(墓地)副本起点' WHERE (`ID`='45');
UPDATE `areatrigger_teleport` SET `Name`='死亡矿井(副本)A-西部荒野' WHERE (`ID`='78');
UPDATE `areatrigger_teleport` SET `Name`='暴风城监狱-(副本)入口' WHERE (`ID`='101');
UPDATE `areatrigger_teleport` SET `Name`='暴风城地窑' WHERE (`ID`='107');
UPDATE `areatrigger_teleport` SET `Name`='暴风城地窑' WHERE (`ID`='109');
UPDATE `areatrigger_teleport` SET `Name`='死亡矿井A门口-西部荒野' WHERE (`ID`='119');
UPDATE `areatrigger_teleport` SET `Name`='死亡矿井B出口-西部荒野' WHERE (`ID`='121');
UPDATE `areatrigger_teleport` SET `Name`='影牙城堡(副本)-银松森林' WHERE (`ID`='145');
UPDATE `areatrigger_teleport` SET `Name`='影牙城堡 -入口' WHERE (`ID`='194');
UPDATE `areatrigger_teleport` SET `Name`='哀嚎洞穴门口-贫瘠之地' WHERE (`ID`='226');
UPDATE `areatrigger_teleport` SET `Name`='哀嚎洞穴(副本)-贫瘠之地' WHERE (`ID`='228');
UPDATE `areatrigger_teleport` SET `Name`='剃刀沼泽门口-贫瘠之地' WHERE (`ID`='242');
UPDATE `areatrigger_teleport` SET `Name`='剃刀沼泽(副本)-贫瘠之地' WHERE (`ID`='244');
UPDATE `areatrigger_teleport` SET `Name`='黑暗深渊(副本)-灰谷' WHERE (`ID`='257');
UPDATE `areatrigger_teleport` SET `Name`='黑暗深渊门口-灰谷' WHERE (`ID`='259');
UPDATE `areatrigger_teleport` SET `Name`='奥达曼(副本)A-荒芜之地' WHERE (`ID`='286');
UPDATE `areatrigger_teleport` SET `Name`='奥达曼门口' WHERE (`ID`='288');
UPDATE `areatrigger_teleport` SET `Name`='诺莫瑞根门口A-丹莫罗' WHERE (`ID`='322');
UPDATE `areatrigger_teleport` SET `Name`='诺莫瑞根(副本)A-丹莫罗' WHERE (`ID`='324');
UPDATE `areatrigger_teleport` SET `Name`='剃刀高地(副本)-贫瘠之地' WHERE (`ID`='442');
UPDATE `areatrigger_teleport` SET `Name`='剃刀高地门口-贫瘠之地' WHERE (`ID`='444');
UPDATE `areatrigger_teleport` SET `Name`='阿塔哈卡神庙(副本)-悲伤沼泽' WHERE (`ID`='446');
UPDATE `areatrigger_teleport` SET `Name`='阿塔哈卡神庙门口-悲伤沼泽' WHERE (`ID`='448');
UPDATE `areatrigger_teleport` SET `Name`='暴风城监狱-门口' WHERE (`ID`='503');
UPDATE `areatrigger_teleport` SET `Name`='诺莫瑞根(副本)B-丹莫罗' WHERE (`ID`='523');
UPDATE `areatrigger_teleport` SET `Name`='诺莫瑞根门口B-丹莫罗' WHERE (`ID`='525');
UPDATE `areatrigger_teleport` SET `Name`='泰达希尔-鲁瑟兰村' WHERE (`ID`='527');
UPDATE `areatrigger_teleport` SET `Name`='泰达希尔-达纳苏斯' WHERE (`ID`='542');
UPDATE `areatrigger_teleport` SET `Name`='血色修道院西(墓地)门口' WHERE (`ID`='602');
UPDATE `areatrigger_teleport` SET `Name`='血色修道院西(大教堂)门口' WHERE (`ID`='604');
UPDATE `areatrigger_teleport` SET `Name`='血色修道院东(军械库)门口' WHERE (`ID`='606');
UPDATE `areatrigger_teleport` SET `Name`='血色修道院东(图书馆)门口' WHERE (`ID`='608');
UPDATE `areatrigger_teleport` SET `Name`='血色修道院西(大教堂)副本起点' WHERE (`ID`='610');
UPDATE `areatrigger_teleport` SET `Name`='血色修道院东(军械库)副本起点' WHERE (`ID`='612');
UPDATE `areatrigger_teleport` SET `Name`='血色修道院东(图书馆)副本起点' WHERE (`ID`='614');
UPDATE `areatrigger_teleport` SET `Name`='暴风城-巫师圣殿' WHERE (`ID`='702');
UPDATE `areatrigger_teleport` SET `Name`='暴风城-巫师圣殿入口' WHERE (`ID`='704');
UPDATE `areatrigger_teleport` SET `Name`='奥达曼门口B-荒芜之地' WHERE (`ID`='882');
UPDATE `areatrigger_teleport` SET `Name`='奥达曼(副本)B-荒芜之地' WHERE (`ID`='902');
UPDATE `areatrigger_teleport` SET `Name`='祖尔法拉克门口-塔纳利斯' WHERE (`ID`='922');
UPDATE `areatrigger_teleport` SET `Name`='祖尔法拉克(副本)-塔纳利斯' WHERE (`ID`='924');
UPDATE `areatrigger_teleport` SET `Name`='奥妮克希亚的巢穴门口-尘泥沼泽' WHERE (`ID`='1064');
UPDATE `areatrigger_teleport` SET `Name`='黑石深渊(副本)-黑石山' WHERE (`ID`='1466');
UPDATE `areatrigger_teleport` SET `Name`='黑石塔-灼热峡谷黑手大厅' WHERE (`ID`='1468');
UPDATE `areatrigger_teleport` SET `Name`='黑石塔-灼热峡谷熔岩之桥' WHERE (`ID`='1470');
UPDATE `areatrigger_teleport` SET `Name`='黑石深渊门口-黑石山' WHERE (`ID`='1472');
UPDATE `areatrigger_teleport` SET `Name`='矿道地铁-铁炉堡' WHERE (`ID`='2166');
UPDATE `areatrigger_teleport` SET `Name`='矿道地铁-暴风城' WHERE (`ID`='2171');
UPDATE `areatrigger_teleport` SET `Name`='矿道地铁-暴风城' WHERE (`ID`='2173');
UPDATE `areatrigger_teleport` SET `Name`='矿道地铁-铁炉堡' WHERE (`ID`='2175');
UPDATE `areatrigger_teleport` SET `Name`='斯坦索姆(副本)B-东瘟疫之地' WHERE (`ID`='2214');
UPDATE `areatrigger_teleport` SET `Name`='斯坦索姆-东瘟疫之地出口A2' WHERE (`ID`='2216');
UPDATE `areatrigger_teleport` SET `Name`='斯坦索姆-东瘟疫之地出口A1' WHERE (`ID`='2217');
UPDATE `areatrigger_teleport` SET `Name`='斯坦索姆门口B-东瘟疫之地' WHERE (`ID`='2221');
UPDATE `areatrigger_teleport` SET `Name`='怒焰裂谷门口-奥格瑞玛' WHERE (`ID`='2226');
UPDATE `areatrigger_teleport` SET `Name`='怒焰裂谷(副本)-奥格瑞玛' WHERE (`ID`='2230');
UPDATE `areatrigger_teleport` SET `Name`='俄特加德要塞- 出口' WHERE (`ID`='4743');
UPDATE `areatrigger_teleport` SET `Name`='奥格瑞玛-(勇者大厅)入口' WHERE (`ID`='2530');
UPDATE `areatrigger_teleport` SET `Name`='暴风城-(勇士大厅)入口' WHERE (`ID`='2534');
UPDATE `areatrigger_teleport` SET `Name`='通灵学院(副本)-西瘟疫之地' WHERE (`ID`='2567');
UPDATE `areatrigger_teleport` SET `Name`='通灵学院门口-西瘟疫之地' WHERE (`ID`='2568');
UPDATE `areatrigger_teleport` SET `Name`='PVP1奥托兰克山谷-部落入口' WHERE (`ID`='2606');
UPDATE `areatrigger_teleport` SET `Name`='PVP1奥托兰克山谷-联盟入口' WHERE (`ID`='2608');
UPDATE `areatrigger_teleport` SET `Name`='奥妮克希亚的巢穴(副本)-尘泥沼泽' WHERE (`ID`='2848');
UPDATE `areatrigger_teleport` SET `Name`='熔火之桥' WHERE (`ID`='2886');
UPDATE `areatrigger_teleport` SET `Name`='熔火之心 - 入口, 里面' WHERE (`ID`='2890');
UPDATE `areatrigger_teleport` SET `Name`='迈拉顿门口B-凄凉之地' WHERE (`ID`='3126');
UPDATE `areatrigger_teleport` SET `Name`='迈拉顿门口A-凄凉之地' WHERE (`ID`='3131');
UPDATE `areatrigger_teleport` SET `Name`='迈拉顿(副本)A-凄凉之地' WHERE (`ID`='3133');
UPDATE `areatrigger_teleport` SET `Name`='迈拉顿(副本)B-凄凉之地' WHERE (`ID`='3134');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌东A(副本)-菲拉斯' WHERE (`ID`='3183');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌东B(副本)-菲拉斯' WHERE (`ID`='3184');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌东C(副本)-菲拉斯' WHERE (`ID`='3185');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌西B(副本)-菲拉斯' WHERE (`ID`='3186');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌西A(副本)-菲拉斯' WHERE (`ID`='3187');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌北(副本)-菲拉斯' WHERE (`ID`='3189');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌西B门口-菲拉斯' WHERE (`ID`='3190');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌西A门口-菲拉斯' WHERE (`ID`='3191');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌北门口-菲拉斯' WHERE (`ID`='3193');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌东A门口-菲拉斯' WHERE (`ID`='3194');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌东B门口-菲拉斯' WHERE (`ID`='3195');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌东C门口-菲拉斯' WHERE (`ID`='3196');
UPDATE `areatrigger_teleport` SET `Name`='厄运之槌东D门口-菲拉斯' WHERE (`ID`='3197');
UPDATE `areatrigger_teleport` SET `Name`='熔火之心之窗 (熔岩) 入口' WHERE (`ID`='3529');
UPDATE `areatrigger_teleport` SET `Name`='黑翼之巢入口-灼热峡谷-燃烧平原-东部王国' WHERE (`ID`='3726');
UPDATE `areatrigger_teleport` SET `Name`='黑翼之巢出口-黑石山-东部王国' WHERE (`ID`='3728');
UPDATE `areatrigger_teleport` SET `Name`='祖尔格拉布(副本)-荆棘谷' WHERE (`ID`='3928');
UPDATE `areatrigger_teleport` SET `Name`='祖尔格拉布门口-荆棘谷' WHERE (`ID`='3930');
UPDATE `areatrigger_teleport` SET `Name`='PVP4阿拉希盆地联盟出口' WHERE (`ID`='3948');
UPDATE `areatrigger_teleport` SET `Name`='PVP4落锤镇部落入口' WHERE (`ID`='3949');
UPDATE `areatrigger_teleport` SET `Name`='熔火之心之窗 入口' WHERE (`ID`='3528');
UPDATE `areatrigger_teleport` SET `Name`='安其拉废墟门口-希利苏斯' WHERE (`ID`='4006');
UPDATE `areatrigger_teleport` SET `Name`='安其拉废墟(副本)-希利苏斯' WHERE (`ID`='4008');
UPDATE `areatrigger_teleport` SET `Name`='安其拉神殿(副本)-希利苏斯' WHERE (`ID`='4010');
UPDATE `areatrigger_teleport` SET `Name`='安其拉神殿门口-希利苏斯' WHERE (`ID`='4012');
UPDATE `areatrigger_teleport` SET `Name`='俄特加德要塞- 入口' WHERE (`ID`='4745');
UPDATE `areatrigger_teleport` SET `Name`='卡拉赞门楼(入口处)' WHERE (`ID`='4131');
UPDATE `areatrigger_teleport` SET `Name`='碎裂大厅出口' WHERE (`ID`='4145');
UPDATE `areatrigger_teleport` SET `Name`='蒸汽洞窟出口' WHERE (`ID`='4147');
UPDATE `areatrigger_teleport` SET `Name`='玛瑟里顿的巢穴出口' WHERE (`ID`='4149');
UPDATE `areatrigger_teleport` SET `Name`='地狱火壁垒' WHERE (`ID`='4150');
UPDATE `areatrigger_teleport` SET `Name`='破碎大厅' WHERE (`ID`='4151');
UPDATE `areatrigger_teleport` SET `Name`='蒸汽洞窟' WHERE (`ID`='4152');
UPDATE `areatrigger_teleport` SET `Name`='玛瑟里顿的巢穴' WHERE (`ID`='4153');
UPDATE `areatrigger_teleport` SET `Name`='地狱火壁垒出口' WHERE (`ID`='4297');
UPDATE `areatrigger_teleport` SET `Name`='到海家尔人类营地之门' WHERE (`ID`='4311');
UPDATE `areatrigger_teleport` SET `Name`='从海家尔到部落营地之门' WHERE (`ID`='4312');
UPDATE `areatrigger_teleport` SET `Name`='从海家尔到暗夜向导村庄生命之树之门' WHERE (`ID`='4313');
UPDATE `areatrigger_teleport` SET `Name`='海家尔山峰入口' WHERE (`ID`='4319');
UPDATE `areatrigger_teleport` SET `Name`='黑色沼泽出口' WHERE (`ID`='4320');
UPDATE `areatrigger_teleport` SET `Name`='时光之穴出口' WHERE (`ID`='4321');
UPDATE `areatrigger_teleport` SET `Name`='黑色沼泽出口' WHERE (`ID`='4322');
UPDATE `areatrigger_teleport` SET `Name`='从海家尔到CoT 主门' WHERE (`ID`='4323');
UPDATE `areatrigger_teleport` SET `Name`='时光之穴入口' WHERE (`ID`='4324');
UPDATE `areatrigger_teleport` SET `Name`='外域到黑暗之门' WHERE (`ID`='4352');
UPDATE `areatrigger_teleport` SET `Name`='黑暗之门到外域' WHERE (`ID`='4354');
UPDATE `areatrigger_teleport` SET `Name`='沼泽洞穴入口' WHERE (`ID`='4363');
UPDATE `areatrigger_teleport` SET `Name`='蒸汽洞窟入口' WHERE (`ID`='4364');
UPDATE `areatrigger_teleport` SET `Name`='奴隶围栏入口' WHERE (`ID`='4365');
UPDATE `areatrigger_teleport` SET `Name`='蒸汽洞窟出口' WHERE (`ID`='4366');
UPDATE `areatrigger_teleport` SET `Name`='沼泽洞穴出口' WHERE (`ID`='4367');
UPDATE `areatrigger_teleport` SET `Name`='奴隶围栏出口' WHERE (`ID`='4379');
UPDATE `areatrigger_teleport` SET `Name`='逐日岛到东瘟疫之地' WHERE (`ID`='4386');
UPDATE `areatrigger_teleport` SET `Name`='暗影迷宫出口' WHERE (`ID`='4397');
UPDATE `areatrigger_teleport` SET `Name`='塞泰克大厅出口' WHERE (`ID`='4399');
UPDATE `areatrigger_teleport` SET `Name`='法力坟墓出口' WHERE (`ID`='4401');
UPDATE `areatrigger_teleport` SET `Name`='奥金顿墓穴出口' WHERE (`ID`='4403');
UPDATE `areatrigger_teleport` SET `Name`='奥金顿墓穴入口' WHERE (`ID`='4404');
UPDATE `areatrigger_teleport` SET `Name`='法力坟墓入口' WHERE (`ID`='4405');
UPDATE `areatrigger_teleport` SET `Name`='塞泰克大厅入口' WHERE (`ID`='4406');
UPDATE `areatrigger_teleport` SET `Name`='暗影迷宫入口' WHERE (`ID`='4407');
UPDATE `areatrigger_teleport` SET `Name`='东瘟疫之地到逐日岛' WHERE (`ID`='4409');
UPDATE `areatrigger_teleport` SET `Name`='盘牙洞穴入口' WHERE (`ID`='4416');
UPDATE `areatrigger_teleport` SET `Name`='卡拉赞门房 (出口)' WHERE (`ID`='4436');
UPDATE `areatrigger_teleport` SET `Name`='拱廊区出口' WHERE (`ID`='4455');
UPDATE `areatrigger_teleport` SET `Name`='凤凰大厅出口' WHERE (`ID`='4457');
UPDATE `areatrigger_teleport` SET `Name`='秘术区出口' WHERE (`ID`='4459');
UPDATE `areatrigger_teleport` SET `Name`='机械区出口' WHERE (`ID`='4461');
UPDATE `areatrigger_teleport` SET `Name`='秘术区入口' WHERE (`ID`='4467');
UPDATE `areatrigger_teleport` SET `Name`='拱廊区入口' WHERE (`ID`='4468');
UPDATE `areatrigger_teleport` SET `Name`='机械区入口' WHERE (`ID`='4469');
UPDATE `areatrigger_teleport` SET `Name`='凤凰大厅入口' WHERE (`ID`='4470');
UPDATE `areatrigger_teleport` SET `Name`='海家尔峰出口' WHERE (`ID`='4487');
UPDATE `areatrigger_teleport` SET `Name`='格鲁尔巢穴出口' WHERE (`ID`='4534');
UPDATE `areatrigger_teleport` SET `Name`='格鲁尔巢穴入口' WHERE (`ID`='4535');
UPDATE `areatrigger_teleport` SET `Name`='黑暗神庙' WHERE (`ID`='4598');
UPDATE `areatrigger_teleport` SET `Name`='黑暗神庙出口' WHERE (`ID`='4619');
UPDATE `areatrigger_teleport` SET `Name`='盘牙洞穴出口' WHERE (`ID`='4418');
UPDATE `areatrigger_teleport` SET `Name`='索克雷萨出口' WHERE (`ID`='4523');
UPDATE `areatrigger_teleport` SET `Name`='祖阿曼入口' WHERE (`ID`='4738');
UPDATE `areatrigger_teleport` SET `Name`='祖阿曼出口' WHERE (`ID`='4739');
UPDATE `areatrigger_teleport` SET `Name`='信仰的飞跃 - 秋季结束' WHERE (`ID`='943');
UPDATE `areatrigger_teleport` SET `Name`='侵略点:灾难 (回归)' WHERE (`ID`='4561');
UPDATE `areatrigger_teleport` SET `Name`='侵略点:灾难 (回归)' WHERE (`ID`='4562');
UPDATE `areatrigger_teleport` SET `Name`='卡拉赞上层' WHERE (`ID`='4135');
UPDATE `areatrigger_teleport` SET `Name`='魔班主任平台出口' WHERE (`ID`='4885');
UPDATE `areatrigger_teleport` SET `Name`='魔班主任平台入口' WHERE (`ID`='4887');
UPDATE `areatrigger_teleport` SET `Name`='太阳之井高地入口' WHERE (`ID`='4889');
UPDATE `areatrigger_teleport` SET `Name`='太阳之井高地出口' WHERE (`ID`='4891');
UPDATE `areatrigger_teleport` SET `Name`='俄特加德要塞- 出口' WHERE (`ID`='4747');
UPDATE `areatrigger_teleport` SET `Name`='俄特加德要塞- 出口' WHERE (`ID`='4741');
UPDATE `areatrigger_teleport` SET `Name`='奈萨斯 70 入口' WHERE (`ID`='4983');
UPDATE `areatrigger_teleport` SET `Name`='奈萨斯 70 出口' WHERE (`ID`='4981');
UPDATE `areatrigger_teleport` SET `Name`='永恒之眼 - 入口' WHERE (`ID`='5246');
UPDATE `areatrigger_teleport` SET `Name`='纳克萨玛斯 - 入口 4' WHERE (`ID`='5191');
UPDATE `areatrigger_teleport` SET `Name`='纳克萨玛斯 - 入口 2' WHERE (`ID`='5192');
UPDATE `areatrigger_teleport` SET `Name`='纳克萨玛斯 - 入口 3' WHERE (`ID`='5193');
UPDATE `areatrigger_teleport` SET `Name`='纳克萨玛斯 - 入口 1' WHERE (`ID`='5194');
UPDATE `areatrigger_teleport` SET `Name`='纳克萨玛斯 - 出口 4' WHERE (`ID`='5196');
UPDATE `areatrigger_teleport` SET `Name`='纳克萨玛斯 - 出口 2' WHERE (`ID`='5197');
UPDATE `areatrigger_teleport` SET `Name`='纳克萨玛斯 - 出口 3' WHERE (`ID`='5198');
UPDATE `areatrigger_teleport` SET `Name`='纳克萨玛斯 - 出口 1' WHERE (`ID`='5199');
UPDATE `areatrigger_teleport` SET `Name`='往事引导 入口' WHERE (`ID`='5150');
UPDATE `areatrigger_teleport` SET `Name`='斯坦索姆的抉择 (出口)' WHERE (`ID`='5181');
UPDATE `areatrigger_teleport` SET `Name`='紫罗兰堡 - 入口' WHERE (`ID`='5209');
UPDATE `areatrigger_teleport` SET `Name`='紫罗兰堡 - 出口' WHERE (`ID`='5211');
UPDATE `areatrigger_teleport` SET `Name`='刚德拉克 - 入口' WHERE (`ID`='5206');
UPDATE `areatrigger_teleport` SET `Name`='刚德拉克 - 入口' WHERE (`ID`='5205');
UPDATE `areatrigger_teleport` SET `Name`='刚德拉克 - 出口 04' WHERE (`ID`='5277');
UPDATE `areatrigger_teleport` SET `Name`='刚德拉克 - 出口 02' WHERE (`ID`='5231');
UPDATE `areatrigger_teleport` SET `Name`='雷光大厅 - 入口' WHERE (`ID`='5093');
UPDATE `areatrigger_teleport` SET `Name`='雷光大厅 - 出口' WHERE (`ID`='5091');
UPDATE `areatrigger_teleport` SET `Name`='奥杜亚, 石之大厅 (入口)' WHERE (`ID`='5010');
UPDATE `areatrigger_teleport` SET `Name`='石之大厅 - 出口' WHERE (`ID`='5012');
UPDATE `areatrigger_teleport` SET `Name`='阿兹欧-奈幽 (入口)' WHERE (`ID`='5117');
UPDATE `areatrigger_teleport` SET `Name`='阿兹欧-奈幽 (出口)' WHERE (`ID`='5115');
UPDATE `areatrigger_teleport` SET `Name`='阿兹欧-奈幽 - 出口?' WHERE (`ID`='5113');
UPDATE `areatrigger_teleport` SET `Name`='阿兹欧-奈幽: 安卡罕特:古王国 - 入口' WHERE (`ID`='5215');
UPDATE `areatrigger_teleport` SET `Name`='古王国 - 出口' WHERE (`ID`='5213');
UPDATE `areatrigger_teleport` SET `Name`='守护巨龙之间, 黑曜圣所 (入口)' WHERE (`ID`='5243');
UPDATE `areatrigger_teleport` SET `Name`='守护巨龙之间, 黑曜圣所 (出口)' WHERE (`ID`='5241');
UPDATE `areatrigger_teleport` SET `Name`='德拉克萨隆 入口' WHERE (`ID`='4998');
UPDATE `areatrigger_teleport` SET `Name`='德拉克萨隆 出口' WHERE (`ID`='5000');
UPDATE `areatrigger_teleport` SET `Name`='永恒之眼 (入口)' WHERE (`ID`='5290');
UPDATE `areatrigger_teleport` SET `Name`='奥核之眼 - 出口' WHERE (`ID`='5001');
UPDATE `areatrigger_teleport` SET `Name`='卡拉赞, 广场 (出口)' WHERE (`ID`='4520');
UPDATE `areatrigger_teleport` SET `Name`='奥杜亚团队 入口' WHERE (`ID`='5379');
UPDATE `areatrigger_teleport` SET `Name`='奥杜亚团队 出口' WHERE (`ID`='5381');
UPDATE `areatrigger_teleport` SET `Name`='亚夏梵穹殿 (出口)' WHERE (`ID`='5262');
UPDATE `areatrigger_teleport` SET `Name`='亚夏梵穹殿 (入口)' WHERE (`ID`='5258');
UPDATE `areatrigger_teleport` SET `Name`='达拉然水井' WHERE (`ID`='5273');
UPDATE `areatrigger_teleport` SET `Name`='十字军试炼 (出口)' WHERE (`ID`='5508');
UPDATE `areatrigger_teleport` SET `Name`='十字军试炼 (入口)' WHERE (`ID`='5503');
UPDATE `areatrigger_teleport` SET `Name`='勇士试炼 (入口)' WHERE (`ID`='5505');
UPDATE `areatrigger_teleport` SET `Name`='勇士试炼 (出口)' WHERE (`ID`='5510');
UPDATE `areatrigger_teleport` SET `Name`='寒冰皇冠城塞 (入口)' WHERE (`ID`='5670');
UPDATE `areatrigger_teleport` SET `Name`='寒冰皇冠城塞 (出口)' WHERE (`ID`='5668');
UPDATE `areatrigger_teleport` SET `Name`='众魂熔炉 (入口)' WHERE (`ID`='5635');
UPDATE `areatrigger_teleport` SET `Name`='倒影大厅 (入口)' WHERE (`ID`='5636');
UPDATE `areatrigger_teleport` SET `Name`='萨伦之渊 (入口)' WHERE (`ID`='5637');
UPDATE `areatrigger_teleport` SET `Name`='众魂熔炉 (出口)' WHERE (`ID`='5642');
UPDATE `areatrigger_teleport` SET `Name`='萨伦之渊 (出口)' WHERE (`ID`='5643');
UPDATE `areatrigger_teleport` SET `Name`='倒影大厅 (出口)' WHERE (`ID`='5646');
UPDATE `areatrigger_teleport` SET `Name`='萨伦之渊 (出口) 倒影大厅 (入口)' WHERE (`ID`='5683');
UPDATE `areatrigger_teleport` SET `Name`='众魂熔炉 (出口) 萨伦之渊 (入口)' WHERE (`ID`='5688');
UPDATE `areatrigger_teleport` SET `Name`='q12710:1楼' WHERE (`ID`='5051');
UPDATE `areatrigger_teleport` SET `Name`='q12710:2楼' WHERE (`ID`='5079');
UPDATE `areatrigger_teleport` SET `Name`='晶红圣殿 (入口)' WHERE (`ID`='5869');
UPDATE `areatrigger_teleport` SET `Name`='晶红圣殿 (出口)' WHERE (`ID`='5872');
UPDATE `areatrigger_teleport` SET `Name`='刚德拉克 - 出口 03' WHERE (`ID`='5276');
UPDATE `areatrigger_teleport` SET `Name`='刚德拉克 - 出口 01' WHERE (`ID`='5233');
UPDATE `areatrigger_teleport` SET `Name`='生态船 - 麦克纳尔' WHERE (`ID`='4612');
UPDATE `areatrigger_teleport` SET `Name`='能源舰- 生态船' WHERE (`ID`='4614');
UPDATE `areatrigger_teleport` SET `Name`='影牙城堡 - 南落目标' WHERE (`ID`='2406');
UPDATE `areatrigger_teleport` SET `Name`='影牙城堡 - 南落目标' WHERE (`ID`='2407');
UPDATE `areatrigger_teleport` SET `Name`='影牙城堡 - 前落目标出口' WHERE (`ID`='2408');
UPDATE `areatrigger_teleport` SET `Name`='影牙城堡 - 前落目标出口' WHERE (`ID`='2409');
UPDATE `areatrigger_teleport` SET `Name`='影牙城堡 - 北落目标' WHERE (`ID`='2410');
UPDATE `areatrigger_teleport` SET `Name`='影牙城堡 - 北落目标' WHERE (`ID`='2411');
UPDATE `areatrigger_teleport` SET `Name`='永歌森林 - Duskwither UP Target' WHERE (`ID`='4233');
UPDATE `areatrigger_teleport` SET `Name`='永歌森林 - Duskwither DOWN Target' WHERE (`ID`='4267');
UPDATE `areatrigger_teleport` SET `Name`='地狱火城墙 - Omor Exit Target' WHERE (`ID`='4304');
UPDATE `areatrigger_teleport` SET `Name`='CoT Stratholme - Exit Target' WHERE (`ID`='5148');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 纳格兰 - Teleport Target - Game On' WHERE (`ID`='4917');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 刀锋山 - Teleport Target - Game On' WHERE (`ID`='4919');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 刀锋山 - Teleport Target - Game On' WHERE (`ID`='4921');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 刀锋山 - Teleport Target - Game On' WHERE (`ID`='4922');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 刀锋山 - Teleport Target - Game On' WHERE (`ID`='4923');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 刀锋山 - Teleport Target - Game On' WHERE (`ID`='4924');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 刀锋山 - Teleport Target - Game On' WHERE (`ID`='4925');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4927');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4928');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4929');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4930');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4931');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4932');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4933');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4934');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4935');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4936');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 幽暗城 - Teleport Target - Game On' WHERE (`ID`='4941');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 刀锋山 - Teleport Target - Game On' WHERE (`ID`='4944');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 达拉然竞技场 - Teleport Target' WHERE (`ID`='5326');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 达拉然竞技场 - Teleport Target' WHERE (`ID`='5328');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 达拉然竞技场 - Teleport Target' WHERE (`ID`='5329');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 达拉然竞技场 - Teleport Target' WHERE (`ID`='5330');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 达拉然竞技场 - Teleport Target' WHERE (`ID`='5331');
UPDATE `areatrigger_teleport` SET `Name`='竞技场 - 奥格瑞玛 - Teleport Target 3' WHERE (`ID`='5447');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) Top Return Target' WHERE (`ID`='5127');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) Top 西部 Target' WHERE (`ID`='5128');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) Top Return Target' WHERE (`ID`='5129');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) Top 南部 Target' WHERE (`ID`='5130');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) Top Return Target' WHERE (`ID`='5131');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) Top 北部 Target' WHERE (`ID`='5132');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) Top Return Target' WHERE (`ID`='5133');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) Top 东部 Target' WHERE (`ID`='5134');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) 中间 -> 底部 Target' WHERE (`ID`='5135');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) 中间 -> 底部 Target' WHERE (`ID`='5136');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) 底部 -> 中间 Target' WHERE (`ID`='5137');
UPDATE `areatrigger_teleport` SET `Name`='黑锋要塞 (E.K.) 底部 -> 地面 Target' WHERE (`ID`='5138');
UPDATE `areatrigger_teleport` SET `Name`='通灵学院- Exit Porch Target 001' WHERE (`ID`='2547');
UPDATE `areatrigger_teleport` SET `Name`='通灵学院 - Exit Porch Target 001' WHERE (`ID`='2548');
UPDATE `areatrigger_teleport` SET `Name`='通灵学院 - Exit Porch Target 001' WHERE (`ID`='2549');
UPDATE `areatrigger_teleport` SET `Name`='Ahn\'Kahet (exit)' WHERE (`ID`='5235');
UPDATE `areatrigger_teleport` SET `Name`='Halls of Reflection (The Impenetrable Door)' WHERE (`ID`='5740');