-- Mangos or Trinitycore 数据库中文支持
-- version 1.0
-- https://git.oschina.net/686500/Wow-ChineseDB

UPDATE `game_event` SET `description`='仲夏焰火节' WHERE (`eventEntry`='1');
UPDATE `game_event` SET `description`='冬幕节' WHERE (`eventEntry`='2');
UPDATE `game_event` SET `description`='暗月马戏团（泰罗卡森林）' WHERE (`eventEntry`='3');
UPDATE `game_event` SET `description`='暗月马戏团（艾尔文森林）' WHERE (`eventEntry`='4');
UPDATE `game_event` SET `description`='暗月马戏团（莫高雷）' WHERE (`eventEntry`='5');
UPDATE `game_event` SET `description`='除夕' WHERE (`eventEntry`='6');
UPDATE `game_event` SET `description`='春节' WHERE (`eventEntry`='7');
UPDATE `game_event` SET `description`='爱意弥漫的天空' WHERE (`eventEntry`='8');
UPDATE `game_event` SET `description`='贵族花园' WHERE (`eventEntry`='9');
UPDATE `game_event` SET `description`='儿童周' WHERE (`eventEntry`='10');
UPDATE `game_event` SET `description`='收获节' WHERE (`eventEntry`='11');
UPDATE `game_event` SET `description`='万圣节' WHERE (`eventEntry`='12');
UPDATE `game_event` SET `description`='安其拉之战' WHERE (`eventEntry`='22');
UPDATE `game_event` SET `description`='天灾入侵' WHERE (`eventEntry`='17');
UPDATE `game_event` SET `description`='元素生物入侵' WHERE (`eventEntry`='13');
UPDATE `game_event` SET `description`='荆棘谷激情钓鱼会' WHERE (`eventEntry`='14');
UPDATE `game_event` SET `description`='古拉巴什竞技场战斗' WHERE (`eventEntry`='16');
UPDATE `game_event` SET `description`='荆棘谷钓鱼大赛VIP' WHERE (`eventEntry`='15');
UPDATE `game_event` SET `description`='战斗的召唤：奥特兰克山谷!' WHERE (`eventEntry`='18');
UPDATE `game_event` SET `description`='战斗的召唤：战歌峡谷!' WHERE (`eventEntry`='19');
UPDATE `game_event` SET `description`='战斗的召唤：阿拉希盆地!' WHERE (`eventEntry`='20');
UPDATE `game_event` SET `description`='战斗的召唤：风暴之眼!' WHERE (`eventEntry`='21');
UPDATE `game_event` SET `description`='暗月马戏团建立（艾尔文森林）' WHERE (`eventEntry`='23');
UPDATE `game_event` SET `description`='美酒节' WHERE (`eventEntry`='24');
UPDATE `game_event` SET `description`='夜幕' WHERE (`eventEntry`='25');
UPDATE `game_event` SET `description`='疯狂之刃, 格里雷克' WHERE (`eventEntry`='27');
UPDATE `game_event` SET `description`='疯狂之刃, 哈扎拉尔' WHERE (`eventEntry`='28');
UPDATE `game_event` SET `description`='疯狂之刃, 雷纳塔基' WHERE (`eventEntry`='29');
UPDATE `game_event` SET `description`='疯狂之刃, 乌苏雷' WHERE (`eventEntry`='30');
UPDATE `game_event` SET `description`='锦标赛竞技场' WHERE (`eventEntry`='31');
UPDATE `game_event` SET `description`='L70ETC牛头酋长乐队' WHERE (`eventEntry`='32');
UPDATE `game_event` SET `description`='冬幕节:礼物' WHERE (`eventEntry`='52');
UPDATE `game_event` SET `description`='亡者节' WHERE (`eventEntry`='51');
UPDATE `game_event` SET `description`='冬握湖联盟防御战' WHERE (`eventEntry`='48');
UPDATE `game_event` SET `description`='冬握湖部落防御战' WHERE (`eventEntry`='49');
UPDATE `game_event` SET `description`='战斗的召唤：远古海滩!' WHERE (`eventEntry`='53');
UPDATE `game_event` SET `description`='竞技场第三赛季' WHERE (`eventEntry`='55');
UPDATE `game_event` SET `description`='竞技场第四赛季' WHERE (`eventEntry`='56');
UPDATE `game_event` SET `description`='竞技场第五赛季' WHERE (`eventEntry`='57');
UPDATE `game_event` SET `description`='竞技场第六赛季' WHERE (`eventEntry`='58');
UPDATE `game_event` SET `description`='竞技场第七赛季' WHERE (`eventEntry`='59');
UPDATE `game_event` SET `description`='竞技场第八赛季' WHERE (`eventEntry`='60');
UPDATE `game_event` SET `description`='战斗的召唤:征服之岛' WHERE (`eventEntry`='54');
UPDATE `game_event` SET `description`='海贼日' WHERE (`eventEntry`='50');
UPDATE `game_event` SET `description`='扎拉赞的沦陷' WHERE (`eventEntry`='61');
UPDATE `game_event` SET `description`='荆棘谷钓鱼大赛' WHERE (`eventEntry`='62');
UPDATE `game_event` SET `description`='卡鲁耶克钓鱼大赛' WHERE (`eventEntry`='63');
UPDATE `game_event` SET `description`='卡鲁耶克钓鱼大赛VIP' WHERE (`eventEntry`='64');
UPDATE `game_event` SET `description`='旅人丰年祭' WHERE (`eventEntry`='26');
UPDATE `game_event` SET `description`='Dalaran: Minigob' WHERE (`eventEntry`='33');
UPDATE `game_event` SET `description`='Perry Gatner' WHERE (`eventEntry`='65');
UPDATE `game_event` SET `description`='Brew of the Month October' WHERE (`eventEntry`='34');
UPDATE `game_event` SET `description`='Brew of the Month November' WHERE (`eventEntry`='35');
UPDATE `game_event` SET `description`='Brew of the Month December' WHERE (`eventEntry`='36');
UPDATE `game_event` SET `description`='Brew of the Month January' WHERE (`eventEntry`='37');
UPDATE `game_event` SET `description`='Brew of the Month February' WHERE (`eventEntry`='38');
UPDATE `game_event` SET `description`='Brew of the Month March' WHERE (`eventEntry`='39');
UPDATE `game_event` SET `description`='Brew of the Month April' WHERE (`eventEntry`='40');
UPDATE `game_event` SET `description`='Brew of the Month May' WHERE (`eventEntry`='41');
UPDATE `game_event` SET `description`='Brew of the Month June' WHERE (`eventEntry`='42');
UPDATE `game_event` SET `description`='Brew of the Month July' WHERE (`eventEntry`='43');
UPDATE `game_event` SET `description`='Brew of the Month August' WHERE (`eventEntry`='44');
UPDATE `game_event` SET `description`='Brew of the Month September' WHERE (`eventEntry`='45');
UPDATE `game_event` SET `description`='AT Event Trigger (Tirion Speech)' WHERE (`eventEntry`='67');
UPDATE `game_event` SET `description`='AT Event Trigger (Horde Event)' WHERE (`eventEntry`='68');
UPDATE `game_event` SET `description`='AT Event Trigger (Alliance Event)' WHERE (`eventEntry`='69');